### ISSUE TITLE
How can I find the log of vasp

### ISSUE THREAD

**Issue by NKUCodingCat** [egplar/vasptest#1]
I just run  the script and got 4 fails, one of them is 
```
Scenario: SO3 
    Given that the POTCAR MD5 is 4823c0c64273f99ca3a80cb37ea000eb
    When I run VASP with a maximum of 16 ranks
      Assertion Failed: VASP exited with error or crashed.
```

So where is the log of vasp (if keeped)...I wanna read the log and find the reason of crashing...

**Comment by mgjf** [comment]
Looking at lines 53-57 of `vasptest/features/steps/steps.py` it appears that the output is discarded. 
Easiest workaround (modify according to your needs - my example is for SGE and OpenMPI):
`export VASPTEST_EXE="mpirun -np $NSLOTS $(which vasp_std) > vasptest.out 2> vasptest.err"`
and then run behave. This will create live output and error files in each test's tmp/_test_ working directory.

**Comment by NKUCodingCat** [comment]
Maybe I worked around or gived up at that time ... but thank you anyway
